<div class="container">
<section class="section">
    <div class="container mt-5">
    <div class="row">
        <div class="col-12 col-sm-10 offset-sm-1 col-md-8 offset-md-2 col-lg-8 offset-lg-2 col-xl-8 offset-xl-2">
        <div class="login-brand">
            <img src="assets/img/vl.png" alt="logo" width="110" class="shadow-light rounded-circle">
        </div>

        <div class="card card-primary">
            <div class="card-header"><h4>User Registration</h4></div>

            
            <?php $this->flashSession->output() ?>
            

            <div class="card-body">
            <form method="POST" action="registerUser">
                <div class="row">
                <div class="form-group col-6">
                    <label for="frist_name">First Name</label>
                    <input id="frist_name" type="text" class="form-control" name="nama_depan" autofocus>
                </div>
                <div class="form-group col-6">
                    <label for="last_name">Last Name</label>
                    <input id="last_name" type="text" class="form-control" name="nama_belakang">
                </div>
                </div>

                <div class="form-group">
                <label for="email">Email</label>
                <input id="email" type="email" class="form-control" name="email">
                <div class="invalid-feedback">
                </div>
                </div>

                <div class="row">
                <div class="form-group col-6">
                    <label for="password" class="d-block">Password</label>
                    <input id="password" type="password" class="form-control pwstrength" data-indicator="pwindicator" name="password">
                    <div id="pwindicator" class="pwindicator">
                    <div class="bar"></div>
                    <div class="label"></div>
                    </div>
                </div>
                <div class="form-group col-6">
                    <label for="password2" class="d-block">Password Confirmation</label>
                    <input id="password2" type="password" class="form-control" name="password-confirm">
                </div>
                </div>

                <div class="row">
                    <div class="form-group col-6">
                    <label for="password" class="d-block">Register Sebagai</label>
                        <select name="role_user" class="form-control">
                            <option value='3'>Mahasiswa</option>
                            <option value='2'>Dosen</option>
                        </select>
                    </div>
                </div>

                <div class="form-group">
                <div class="custom-control custom-checkbox">
                    <input type="checkbox" name="agree" class="custom-control-input" id="agree">
                    <label class="custom-control-label" for="agree">I agree with the terms and conditions</label>
                </div>
                </div>

                <div class="form-group">
                <button type="submit" class="btn btn-primary btn-lg btn-block">
                    Register
                </button>
                </div>
            </form>
            </div>
        </div>
        <div class="simple-footer">
            Copyright &copy; Vilab RAP - 18.12.0986
        </div>
        </div>
    </div>
    </div>
</section>
</div>