<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <title>Phalcon PHP Framework</title>
          <!-- General CSS Files -->
          <link rel="stylesheet" href="<?php echo BASE_URL; ?>public/assets/modules/bootstrap/css/bootstrap.min.css">
          <link rel="stylesheet" href="<?php echo BASE_URL; ?>public/assets/modules/fontawesome/css/all.min.css">

          <!-- CSS Libraries -->
          <link rel="stylesheet" href="<?php echo BASE_URL; ?>public/assets/modules/bootstrap-social/bootstrap-social.css">
          <?php $this->assets->outputCss(); ?>

          <!-- Template CSS -->
          <link rel="stylesheet" href="<?php echo BASE_URL; ?>public/assets/css/style.css">
          <link rel="stylesheet" href="<?php echo BASE_URL; ?>public/assets/css/components.css">
        <!-- Start GA -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=UA-94034622-3"></script>
        <script>
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());

          gtag('config', 'UA-94034622-3');
        </script>
        <!-- /END GA -->
    </head>
    <body>
        <div class="container">
            <?php echo $this->getContent(); ?>
        </div>
        <!-- General JS Scripts -->
        <script src="<?php echo BASE_URL; ?>public/assets/modules/jquery.min.js"></script>
        <script src="<?php echo BASE_URL; ?>public/assets/modules/popper.js"></script>
        <script src="<?php echo BASE_URL; ?>public/assets/modules/tooltip.js"></script>
        <script src="<?php echo BASE_URL; ?>public/assets/modules/bootstrap/js/bootstrap.min.js"></script>
        <script src="<?php echo BASE_URL; ?>public/assets/modules/nicescroll/jquery.nicescroll.min.js"></script>
        <script src="<?php echo BASE_URL; ?>public/assets/modules/moment.min.js"></script>
        <script src="<?php echo BASE_URL; ?>public/assets/js/stisla.js"></script>
        
        <!-- JS Libraies -->
        <?php $this->assets->outputJs(); ?>
        <!-- Page Specific JS File -->
        
        <!-- Template JS File -->
        <script src="<?php echo BASE_URL; ?>public/assets/js/scripts.js"></script>
        <script src="<?php echo BASE_URL; ?>public/assets/js/custom.js"></script>
      
    </body>
</html>
